Cargo.lock, crates/composer/Cargo.toml, crates/composer/src/lib.rs, crates/composer/src/schema.rs
this parser allows to analyze and validated `composer.json` easily.
there is no plan to introduce any features to fennec in the time being that would replace `composer` binary, however, we can use this parser to provide better UX in fennec, by using `composer.json` to initialize fennec project ( see #6 ), or scan for packages with known security vunerabilies.
=> feat: add a composer.json parser

crates/ast/src/ast/modifier.rs, crates/ast/src/node.rs, crates/formatter/src/format/mod.rs, crates/lexer/src/lib.rs, crates/linter/src/plugin/redundancy/mod.rs, crates/linter/src/plugin/redundancy/rules/mod.rs, crates/linter/src/plugin/redundancy/rules/redundant_write_visibility.rs, crates/parser/src/internal/modifier.rs, crates/semantics/src/walker.rs, crates/token/src/lib.rs
`protected(set)` and `public(set)` are semantically valid.  `public public(set)` is silly but valid PHP code. PHP doesn't warn or error because of the identical visibilities.
I've added a new linter rule to tell you that the additional write visibility is redundant too:
Side note - I've marked the fix as potentially unsafe since there could be a reason for having identical read/write visibilities, but also happy to change that to a safe fix since it doesn't really have an effect.
=> Add support for `protected(set)` and `public(set)`

crates/linter/src/plugin/compatibility/mod.rs, crates/linter/src/plugin/compatibility/rules/mod.rs, crates/linter/src/plugin/compatibility/rules/php74/arrow_functions_feature.rs, crates/php-version/src/feature.rs, crates/php-version/src/lib.rs
This is my first attempt at writing a lint!
In order to test it out properly, the `MINIMUM_PHP_VERSION` needs to be lowered to `PHP73` since arrow functions are available on PHP 7.4+. (note: there is currently an issue with "Null Coalesce Assignment Feature" that warns for `php_version = "7.4"` see more info here: https://github.com/carthage-software/mago/commit/95a84ce80e9d90b007190e2892fd7f6a60ab9806#r151496707)
https://github.com/carthage-software/mago/blob/dc326633ff8fdd49ca21803e1a7d3d59780fb924/src/consts.rs#L52
I have done that locally, and the lint seems to be working! 🎉
=> Add compatibility/arrow-functions-feature lint

composer.json, composer.lock
This pull request includes a change to the `composer.json` file to update the PHP version requirements.
* [`composer.json`](diffhunk://#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34L16-R16): Updated the [PHP version](https://www.php.net/supported-versions.php) requirements to include versions 8.1 and 8.2 in addition to the previously supported versions 8.3 and 8.4.
=> Composer: Allow all supported PHP versions

composer/MagoPlugin.php
The code of the composer plugin is not compatible with PHP 8.1.
Now it is.
=> Make composer plugin compatible with PHP 8.1

crates/lexer/src/internal/consts.rs, crates/lexer/src/lib.rs, crates/lexer/tests/tokenizer.rs, crates/linter/src/plugin/best_practices/mod.rs, crates/linter/src/plugin/best_practices/rules/mod.rs, crates/linter/src/plugin/best_practices/rules/no_hash_emoji.rs, crates/linter/tests/plugins/best_practices.rs
This PR extends the lexer to support the #️⃣ (hash emoji) as a valid alternative to the ASCII # symbol in comments and attribute declarations, and introduces a new linter rule (No Hash Emoji) that warns developers if they use the emoji-based character instead of the normal #.
Certain codebases or editors may inadvertently introduce the #️⃣ emoji in place of #, and although our lexer can parse it correctly, it may cause confusion for maintainers or break external tools expecting plain ASCII. We wanted to ensure compatibility in parsing while also discouraging this usage for practical reasons.
- **Lexer**: Recognizes #️⃣ as equivalent to # for comments and attribute declarations.
- **Linter**: Added the No Hash Emoji rule, which issues a warning if #️⃣ is detected, suggesting replacing it …
=> feat(lexer/linter): add support for #️⃣ hash emoji & corresponding linter rule

crates/lexer/src/internal/consts.rs, crates/lexer/src/lib.rs, crates/lexer/tests/tokenizer.rs, crates/linter/src/plugin/best_practices/rules/no_hash_emoji.rs
Previously, we extended the lexer to parse the  emoji for attribute declarations. However, PHP does not support it for attributes, so we are reverting that lexer change. We also updated `NoHashEmojiRule` to clearly warn that using  in attributes doesn’t parse at all, while still discouraging its use in comments for clarity and tooling compatibility.
This PR removes the previously added lexer support for the #️⃣ emoji in attribute declarations (since PHP does not actually parse it) and updates the `NoHashEmojiRule` to reflect that #️⃣ in attributes is entirely invalid. The rule now clearly warns that the emoji will not parse in attributes and can confuse or break tooling in comments as well.
- We want to revert the lexer changes to avoid misleading users into believing they can use #️⃣ for …
=> revert: remove  emoji support in lexer and update NoHashEmojiRule

Cargo.lock, Cargo.toml, Justfile, crates/reference/Cargo.toml, crates/reference/src/internal/context.rs, crates/reference/src/internal/mod.rs, crates/reference/src/internal/walker.rs, crates/reference/src/lib.rs, crates/reference/src/query.rs, src/commands/find.rs, src/commands/mod.rs, src/main.rs
This PR introduces a new crate, **mago_reference**, which implements advanced symbol reference searching capabilities for PHP projects. It adds a new CLI command, `mago find [query]`, that allows users to locate symbol references (including imports, uses, definitions, etc.) in both user-defined and external sources.
The motivation behind this change is to enhance code analysis for PHP projects by providing a robust, flexible search tool. Developers can now quickly locate symbol references across large codebases using an expressive query syntax. This feature is particularly valuable for navigating complex projects and for integration with future Language Server Protocol (LSP) workflows.
- **Feature:** Introduced the new **mago_reference** crate, which focuses on symbol reference search …
=> feat: introduce reference crate, and find cli command

docs/getting-started/configuration.md, src/commands/format.rs, src/config/formatter.rs
This PR adds support for an `excludes` configuration option under the `[format]` section in `mago.toml`. With this new option, users can specify files, directories, or glob patterns that will be excluded from formatting operations. These files will not be modified during the formatting process, but they remain active for linting and other analysis tasks.
Several users have requested more granular control over formatting behavior. In many projects, there are files or directories (such as generated files ) that should not be reformatted by the tool. Prior to this change, Mago would format every file found during its scan, which sometimes led to unintended modifications.
By introducing an `excludes` option under `[format]`, users now have the ability to tailor the formatting process. They …
=> feat(cli): allow excluding patterns from formatter

crates/formatter/src/lib.rs, crates/formatter/tests/comment/mod.rs, crates/formatter/tests/comment/single_line.rs, crates/formatter/tests/mod.rs, src/config/formatter.rs
Fix formatting trailing comments after an opening tag ( e.g `<?php` ) and dangling comments inside of blocks.
N/A
N/A
N/A
N/A
=> fix(formatter): fix formatting trailing and dangling comments

docs/_sidebar.md, docs/recipes/ci.md
This PR adds a Recipes section to the docs, as well as instructions for setting up Mago in GitHub Actions
Improve the CI experience
- **Docs:** Added CI recipes
n/a
n/a
=> docs: add ci recipes

composer/InstallMagoBinaryCommand.php
This PR fixes the composer plugin always installing the latest binary.
The issue is that `InstalledVersions::getVersion()` returned `0.10.0.0` and the `tag_name` from github is `0.10.0`.
By using `InstalledVersions::getPrettyVersion()` we get `0.10.0` instead.
Also cast `$release['id']` to string to ensure it is a string.
(`Mago\InstallMagoBinaryCommand::detectMagoReleaseId(): Return value must be of type string, int returned`)
I had some issues with mago 0.11.0, and wanted to stay in 0.10.0 but it kept installing the latest binary.
- **Bug Fix:** Fix composer installer to install correct binary
I have never used these composer utils before, so I might be doing something wrong. When I tested it worked as expected.
=> fix: versions always mismatching when detecting release

crates/ast/src/ast/use.rs, crates/formatter/src/format/mod.rs, crates/formatter/src/format/statement.rs, crates/formatter/src/settings.rs, crates/formatter/tests/format/mod.rs, crates/formatter/tests/format/statement.rs, docs/formatter/settings.md, src/config/formatter.rs
This PR introduces three new settings to the formatter: `sort_uses`, `separate_use_types`, and `expand_use_groups`. These settings control the formatting of use statements in PHP code, allowing for sorting, grouping by type (function, const, or regular), and expanding grouped use statements into individual statements.
Currently, the formatter has limited control over use statement formatting. This PR addresses user requests for more control over the organization of imports, enhancing code readability and maintainability. It provides options similar to those found in other popular code formatters and linters (e.g., isort in Python, various linters in JavaScript).  Sorting and grouping imports can significantly improve the structure and clarity of large codebases.
- **Feature:** Added …
=> feat(formatter): sort, expand, and separate use statements

crates/ast/src/ast/construct.rs, crates/ast/src/ast/statement.rs, crates/ast/src/ast/terminator.rs, crates/formatter/src/document/mod.rs, crates/formatter/src/format/statement.rs, crates/formatter/src/parens.rs, crates/formatter/src/printer/command.rs, crates/formatter/src/printer/mod.rs, crates/formatter/src/settings.rs, crates/formatter/src/utils.rs, crates/formatter/tests/format/mixed.rs, crates/formatter/tests/format/mod.rs, crates/source/src/lib.rs
This PR adds the `Align` document type to the formatter and fixes bugs related to the indentation and alignment of PHP code within HTML files. It also includes several new tests to ensure the correctness of the formatter.
The formatter was not handling the indentation and alignment of PHP code within HTML files correctly. This was due to the lack of a proper mechanism to align the content based on the indentation of the opening tag. This PR introduces the `Align` document type, which allows for more precise control over indentation and alignment, similar to the `align` type in Prettier.js. This change ensures that PHP code within HTML files is formatted consistently and correctly.
- **Feature:** Added `Align` document type to the formatter.
- **Bug Fix:** Fixed incorrect indentation and …
=> fix(formatter): fix alignment of indented php code within html

crates/formatter/src/document/group.rs, crates/formatter/src/document/mod.rs, crates/formatter/src/format/mod.rs, crates/formatter/src/lib.rs, crates/formatter/src/printer/mod.rs, crates/formatter/src/settings.rs, crates/formatter/src/utils.rs, crates/formatter/tests/format/mod.rs, docs/formatter/settings.md, src/config/formatter.rs
This PR introduces a new formatter option `remove_trailing_close_tag` to control whether the trailing `?>` tag should be removed from PHP files.
Previously, the formatter always removed the trailing `?>` tag from PHP files. This behavior is consistent with the PSR/PER coding standard, but it can be undesirable in some cases. This PR adds an option to make this behavior configurable, allowing users to choose whether to keep or remove the trailing closing tag.
Additionally, the previous implementation sometimes left trailing newlines when removing the closing tag, which could lead to inconsistent formatting after a second run of the formatter. This PR fixes this issue by ensuring that trailing newlines are removed at the same time the closing tag is removed.
- **Feature:** Added …
=> feat(formatter): add `remove_trailing_close_tag` option

crates/formatter/src/format/mod.rs, crates/formatter/src/settings.rs, crates/formatter/tests/format/mod.rs, docs/formatter/settings.md, src/config/formatter.rs
This PR adds a new formatter option `space_before_enum_backing_type_hint_colon` to control whether a space should be added before the colon in enum type hints (e.g., `enum Foo: int` vs `enum Foo : int`).
Currently, the formatter does not add a space before the colon in enum type hints. However, some users may prefer to have a space for better readability. This PR introduces a configuration option to accommodate this preference, making the formatter more flexible.
- **Feature:** Added space_before_enum_backing_type_hint_colon option to the formatter.
- **Tests:** Added new tests to verify the behavior of the new option.
- **Docs:** Updated formatter settings documentation to include the new option.
=> feat(formatter): add `space_before_enum_backing_type_hint_colon` option

Cargo.lock, crates/formatter/Cargo.toml, crates/formatter/src/format/call.rs, crates/formatter/src/format/call_arguments.rs, crates/formatter/src/format/call_node.rs, crates/formatter/src/format/expression.rs, crates/formatter/src/lib.rs, crates/formatter/src/parens.rs, crates/formatter/src/settings.rs, crates/formatter/tests/mod.rs, crates/formatter/tests/parens/callee.rs, crates/wasm/src/analysis.rs, crates/wasm/src/lib.rs, docs/formatter/settings.md, src/commands/format.rs, src/config/formatter.rs
This PR adds new configuration options to the formatter to control the use of parentheses in `new` expressions, `exit`, and `die` constructs. It also includes a breaking change that requires a PHP version to be specified when using the formatter.
This change is needed to provide users with more flexibility in how the formatter handles parentheses in different contexts. The new options allow for greater control over code style and consistency. The breaking change is necessary to support the new option that controls parentheses around instantiation in member access chains, as this behavior is version-dependent.
- **Feature:** Added parentheses_around_new_in_member_access option to control parentheses around instantiation in member access chains.
- **Feature:** Added …
=> feat(formatter): add options to control parentheses in new expressions, exit, and die

crates/formatter/src/format/call.rs, crates/formatter/src/format/expression.rs, crates/formatter/tests/format/call.rs, crates/formatter/tests/format/mod.rs
This PR enhances the formatter to support fluent member access chains and expands the handling of member access chains to include property accesses in addition to method calls.
This change is motivated by the desire to improve the formatting of chained method and property access expressions. The addition of fluent member access chains allows for more concise and readable formatting when a pattern of alternating property access and method calls is detected. Expanding the handling of member access chains to include property access ensures that the formatter can handle a wider range of expressions and produce more consistent output.
- **Feature:** Added support for fluent member access chains, allowing for more concise formatting of alternating property access and method calls.
- …
=> feat(formatter): add support for fluent member access chain

crates/formatter/src/format/call.rs, crates/formatter/src/format/misc.rs, crates/formatter/tests/format/call.rs, crates/formatter/tests/parens/callee.rs
This PR refines the formatting of method call chains by adding support for static method calls at the beginning of chains, adjusting the handling of arguments within chains, and modifying the line breaking behavior of chains.
These changes aim to improve the readability and consistency of method call chain formatting.
- Adding static method calls to chains provides a more complete handling of chained calls.
- Preventing argument "hugging" for chained calls allows for better visual flow and avoids unnecessary compactness.
- Using softlines instead of hardlines between chain members provides more flexibility in formatting, allowing chains to stay on a single line when possible.
- Adjusting the parent node breaking behavior ensures that regular method chains don't force unnecessary line …
=> fix(formatter): better handling of member access chains

crates/formatter/src/format/misc.rs, crates/formatter/tests/format/arguments.rs
This PR refines the formatter's behavior regarding "hugging" instantiation expressions within argument lists. It introduces logic to determine when to hug a `new` expression, based on the characteristics of the expression and its arguments.
Previously, the formatter never "hugged" new expressions within argument lists. This could lead to inconsistent and sometimes less readable formatting.
This PR aims to improve the readability and consistency of formatting new expressions in argument lists by introducing specific rules for when to hug them. This ensures that the formatting is both compact and clear.
- **Feature:** Introduced logic for "hugging" new expressions within argument lists:
- Now hugs new expressions if they are a simple class instantiation without arguments.
- Now hugs new …
=> feat(formatter): hug single instantiation arguments

crates/formatter/src/format/call_arguments.rs, crates/formatter/tests/format/arguments.rs
This PR enhances the formatter's argument expansion logic to support expanding the last argument in a function call when it is a new expression with multiple named arguments.
The formatter already has logic to expand the last argument in a function call under certain conditions, such as when it's an array or a similar expression. This helps improve readability by preventing overly long lines and deeply nested expressions.
This PR extends this logic to also expand the last argument when it is a new expression with multiple named arguments. This is because such expressions can also become quite lengthy and benefit from being expanded for better visual clarity.
- **Feature:** Added support for expanding the last argument in a function call when it is a new expression with multiple named …
=> feat(formatter): expand last instantiation argument

docs/formatter/settings.md
Remove references to `method_chain_break_threshold` option
=> docs(formatter): Remove references to `method_chain_break_threshold` option

crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/tests/cases/argument_list_comments/after.php, crates/formatter/tests/cases/argument_list_comments/before.php, crates/formatter/tests/cases/argument_list_comments/settings.inc, crates/formatter/tests/mod.rs
This PR improves the handling of comments within and around argument lists in function calls. It ensures that comments are properly formatted and preserved in their original positions relative to the parentheses and arguments.
The previous formatting logic for argument lists didn't handle comments around parentheses and within the list consistently. This could lead to misplacement of comments, especially in cases with complex argument lists or multiple comments.
- **Feature:** Improved comment handling in argument lists.
- **Tests:** Added a new test case (argument_list_comments) to verify the correct formatting of comments in various positions within and around argument lists.
Closes #81
=> formatter: improve the handling of comments around argument lists

Cargo.lock, Cargo.toml, docs/getting-started/README.md, src/commands/init.rs, src/commands/mod.rs, src/consts.rs, src/error.rs, src/main.rs, src/utils/mod.rs, src/utils/version.rs
This PR adds a new `mago init` command to the Mago CLI, providing an interactive way to initialize a `mago.toml` configuration file. It also updates the documentation to guide users through the new initialization process.
This change is motivated by the desire to simplify the initial setup of Mago for new users. By providing an interactive command, users can easily generate a basic `mago.toml` configuration file tailored to their project, without having to manually create and edit the file. This improves the user experience and makes it easier to get started with Mago.
- **Feature:** Added mago init command to interactively generate a mago.toml configuration file.
- **Docs:** Updated the "Getting Started" guide to include the mago init command and explain how to use it.
Closes #6
=> feat(cli): add `mago init` command with `composer.json` support

crates/ast/src/ast/unary.rs, crates/formatter/src/internal/format/expression.rs, crates/formatter/src/settings.rs, crates/formatter/tests/cases/space_after_not_operator/after.php, crates/formatter/tests/cases/space_after_not_operator/before.php, crates/formatter/tests/cases/space_after_not_operator/settings.inc, crates/formatter/tests/mod.rs, docs/formatter/settings.md, src/config/formatter.rs
This PR introduces a new `space_after_not_operator` option which when enabled will add a space between `!` and the expression.
This feature was requested in #99 
- **Feature:** Added `space_after_not_operator` formatter option.
- **Docs:** Updated formatter settings docs to include the new `space_after_not_operator` option.
Closes #99
=> feat(formatter): introduce an option to add a space before `!` prefix operator

crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/tests/cases/breaking_named_arguments/after.php, crates/formatter/tests/cases/breaking_named_arguments/before.php, crates/formatter/tests/cases/breaking_named_arguments/settings.inc, crates/formatter/tests/mod.rs
This PR introduces changes to when the formatter breaks arguments list.
The logic remains the same as before, with an additional case where if the argument list contains 2 or more arguments, and all arguments are named arguments, the list will always be broken into multiple lines for readability.
See #100 
- **Feature:** Introduce a new case in the formatter that causes argument lists to always break into multiple lines if they contain 2 or more arguments, all of which are named arguments.
=> feat(formatter): always breaking arguments list if it contains only named arguments

crates/formatter/src/document/group.rs, crates/formatter/src/document/mod.rs, crates/formatter/src/internal/comment/format.rs, crates/formatter/src/internal/format/block.rs, crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/src/internal/format/mod.rs, crates/formatter/src/internal/format/parameters.rs, crates/formatter/tests/cases/break_fn_args/after.php, crates/formatter/tests/cases/break_fn_args/before.php, crates/formatter/tests/cases/break_fn_args/settings.inc, crates/formatter/tests/mod.rs
This PR fixes a bug in the formatter which resulted in the parameter list of any function-like node to be broken into multiple lines when it had no parameters, and also fixes an issue with parameter lists missing inner comments in some cases.
This PR also fixes a bug in the formatting of argument lists where in some cases arguments will lose their comments due to being formatted more than once.
The bug was reported by a user in #100 
- **Bug Fix:** Fixed incorrect handling of parameter lists in the formatter.
=> fix(formatter): never break parameter list that is empty, unless comments break it

crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/member_access.rs, crates/formatter/src/internal/format/misc.rs, crates/formatter/tests/cases/member_access_chain/after.php, crates/formatter/tests/cases/member_access_chain/before.php, crates/formatter/tests/cases/member_access_chain/settings.inc, crates/formatter/tests/mod.rs
This PR improves the member access chain eligiblity logic, and adds a new condition of to when a chain will always break.
This improvement is implemented as part of a. series of fixes to the formatter to help improve the output as reported in issues #100 
- **Feature:** Improved the formatter member access chain eligiblity logic.
=> feat(formatter): improve the member access chaining eligiblity logic

composer/InstallMagoBinaryCommand.php, crates/formatter/src/internal/format/mod.rs, crates/formatter/tests/cases/return_wrapping/after.php, crates/formatter/tests/cases/return_wrapping/before.php, crates/formatter/tests/cases/return_wrapping/settings.inc, crates/formatter/tests/mod.rs
Previously, if the expression on the right side of a return statement is a binary operation, it will always be wrapped within parenthesis if it breaks into multiple lines, this has now been adjusted to not wrap binary operations if either sides is a simple expression ( e.g literal, simple word ).
This change was requested in issue #100 to provide better readability.
- **Feature:** Avoid wrapping return valie in parenthesis if its a binary operation, and either sides is a simple expression.
=> feat(formatter): do not wrap return value if its a binary and either sides is a simple expression

crates/ast/src/ast/argument.rs, crates/ast/src/ast/call.rs, crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/misc.rs, crates/formatter/src/internal/format/mod.rs, crates/formatter/src/internal/format/return_value.rs, crates/formatter/tests/cases/arrow_return/after.php, crates/formatter/tests/cases/arrow_return/before.php, crates/formatter/tests/cases/arrow_return/settings.inc, crates/formatter/tests/mod.rs
This PR improves the formatting of arrow functions in two main ways:
- Consistent formatting with return statements: The expression on the right-hand side of an arrow function is now formatted using the same logic as return statement values. This means that in some cases, the expression might be wrapped in parentheses for better readability, especially when it spans multiple lines.
- Improved argument list breaking: When an arrow function is the only argument in a function call, and that arrow function has a simple expression or a function-call-like expression with simple arguments, the formatter will now break the argument list into multiple lines before breaking the arrow function's expression. This makes the code easier to read and understand.
This PR addresses issues raised in #100 …
=> feat(formatter): improve arrow function formatting.

crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/printer/mod.rs, crates/formatter/tests/cases/match_breaking/after.php, crates/formatter/tests/cases/match_breaking/before.php, crates/formatter/tests/cases/match_breaking/settings.inc, crates/formatter/tests/mod.rs
This PR fixes a bug in the formatter that caused incorrect formatting of the `default` arm in `match` expressions.
The formatter was not handling the `default` arm in `match` expressions correctly, leading to inconsistent and sometimes confusing indentation and spacing. This PR addresses this issue by correcting the formatting logic for default arms.
- **Bug Fix**: Corrected the formatting of the default arm in match expressions.
- **Tests**: Added new test cases to verify the correct formatting of default arms.
=> fix(formatter): correct formatting of default arm in match expressions

crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/mod.rs, crates/formatter/src/settings.rs, docs/formatter/settings.md, src/config/formatter.rs
This PR removes the `keyword_case` option from the formatter configuration.
The `keyword_case` option allowed users to control the casing of keywords (e.g., `class`, `function`, `if`) in the formatted output. However, this option is rarely used, and changing the casing of keywords can lead to code that deviates from standard conventions.
This PR removes this option to simplify the formatter configuration and ensure that keywords are always formatted in lowercase, promoting consistency and adherence to common practices.
- **Refactor:** Removed the keyword_case option from the formatter configuration.
- **Refactor:** Keywords are now always formatted in lowercase.
- **Test:** Updated tests to reflect the removal of the option and the consistent lowercase formatting of keywords.
=> refactor(formatter): remove `keyword_case` option

Cargo.lock, Cargo.toml, crates/formatter/Cargo.toml, crates/formatter/src/internal/comment/format.rs, crates/formatter/src/internal/format/array.rs, crates/formatter/tests/cases/array_alignment/after.php, crates/formatter/tests/cases/array_alignment/before.php, crates/formatter/tests/cases/array_alignment/settings.inc, crates/formatter/tests/mod.rs
This PR introduces a new table-style formatting feature for arrays, enhancing the readability of arrays with consistent, simple elements. It also includes checks to prevent table-style formatting for overly wide arrays and refines the detection of suitable arrays for this formatting style.
This PR aims to improve the readability of arrays by introducing a new formatting style that aligns elements in a table-like format. This is particularly beneficial for arrays with consistent elements, such as those used for data structures or configuration. The checks for maximum row width and the refined detection logic ensure that this formatting style is applied appropriately and effectively.
- **Feature:** Introduced table-style formatting for arrays, aligning elements in a table-like format.
- …
=> feat(formatter): add support for formatting table-style arrays

crates/formatter/src/internal/format/binaryish.rs, crates/formatter/tests/cases/binary_alignment/after.php, crates/formatter/tests/cases/binary_alignment/before.php, crates/formatter/tests/cases/binary_alignment/settings.inc, crates/formatter/tests/cases/binary_alignment_before_op/after.php, crates/formatter/tests/cases/binary_alignment_before_op/before.php, crates/formatter/tests/cases/binary_alignment_before_op/settings.inc, crates/formatter/tests/cases/binary_ops_wrapping/after.php, crates/formatter/tests/mod.rs
This PR fixes a bug in the formatter that caused incorrect indentation of multi-line binary expressions within parentheses.
The formatter was not correctly indenting subsequent lines in multi-line binary expressions that were enclosed in parentheses, such as those commonly found in if statement conditions. This resulted in misaligned code and reduced readability. This PR addresses this issue by ensuring that the indentation is applied correctly in these scenarios.
- **Bug Fix:** Fixed incorrect indentation of multi-line binary expressions within parentheses.
- **Tests:** Added new test cases to verify the correct indentation of binary expressions in various contexts.
=> fix(formatter): indent binary operations when split into multple lines inside parenthesis

crates/formatter/src/internal/format/member_access.rs, crates/formatter/tests/cases/chain_comments/after.php, crates/formatter/tests/cases/chain_comments/before.php, crates/formatter/tests/cases/chain_comments/settings.inc, crates/formatter/tests/mod.rs
This PR fixes a bug in the formatter that caused comments in member access chains to be printed after the access operator (`->` or `?->`) instead of before it.
The formatter was incorrectly positioning comments within member access chains, leading to misaligned and less readable code. This PR addresses this issue by ensuring that comments are printed in their correct location, before the access operator, preserving the intended code structure and improving readability.
- **Bug Fix:** Fixed the printing of comments in member access chains to ensure they are positioned before the access operator.
- **Tests:** Added new test cases to verify the correct placement of comments in member access chains.
=> fix(formatter): fix printing member access chain comments

crates/formatter/src/internal/format/array.rs, crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/src/internal/format/call_node.rs, crates/formatter/src/internal/format/class_like.rs, crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/member_access.rs, crates/formatter/src/settings.rs, docs/formatter/settings.md, src/config/formatter.rs
This PR adds new configuration options to the formatter, allowing for more precise control over the formatting of arrays, named arguments, and attributes.
This change is motivated by the desire to provide users with greater flexibility and control over the formatting of their code. The new options allow for fine-tuning the formatting of specific language constructs to better suit individual preferences and project conventions.
- **Feature:** Added array_table_style_alignment option to control the use of table-style alignment for arrays.
- **Feature:** Added always_break_named_arguments_list option to control the breaking of named argument lists.
- **Feature:** Added always_break_attribute_named_argument_lists option to control the breaking of named argument lists in attributes.
- …
=> feat(formatter): add options to control formatting of arrays, named arguments, and attributes

crates/linter/src/plugin/best_practices/rules/no_boolean_flag_parameter.rs
This PR fixes an issue in `best-practices/no-boolean-flag-parameter` rule to allow for promoted properties to have `bool` type.
This change addresses a bug reported in issue #110 where the 
`no-boolean-flag-parameter` rule was not correctly handling promoted properties. Promoted properties, while having a bool type, are fundamentally different from boolean flags passed as function parameters. This rule is intended to discourage the use of boolean flags as parameters, as they can make code harder to understand and maintain. However, promoted properties do not have the same drawbacks and should not be flagged by this rule.
- **Feature:** Updated the best-practices/no-boolean-flag-parameter rule to correctly handle promoted properties with bool types.
- **Feature:** Added new test cases to …
=> fix(linter): ignore boolean promoted properties in `best-practices/no-boolean-flag-parameter`

crates/linter/src/plugin/mod.rs, crates/linter/src/plugin/psl/mod.rs, crates/linter/src/plugin/psl/rules/array_functions.rs, crates/linter/src/plugin/psl/rules/data_structures.rs, crates/linter/src/plugin/psl/rules/datetime.rs, crates/linter/src/plugin/psl/rules/math_functions.rs, crates/linter/src/plugin/psl/rules/mod.rs, crates/linter/src/plugin/psl/rules/output.rs, crates/linter/src/plugin/psl/rules/randomness_functions.rs, crates/linter/src/plugin/psl/rules/regex_functions.rs, crates/linter/src/plugin/psl/rules/sleep_functions.rs, crates/linter/src/plugin/psl/rules/string_functions.rs, crates/linter/src/plugin/psl/rules/utils.rs, crates/linter/tests/plugins/mod.rs, crates/linter/tests/plugins/psl.rs, src/commands/init.rs
This PR introduces a new linter plugin for the PHP Standard Library (Psl) and enhances the `mago init` command to automatically detect and enable the plugin when initializing a project with a `composer.json` file that utilizes Psl.
The new Psl plugin provides rules that encourage the use of Psl functions over their built-in PHP counterparts. This promotes better code style, type safety, and consistency when using Psl in a project.
Enhancing the `mago init` command to automatically detect and enable the Psl plugin when appropriate improves the developer experience by streamlining the configuration process and encouraging the adoption of best practices for Psl usage.
- **Feature:** Added a new linter plugin for the PHP Standard Library (Psl).
- **Feature:** Updated the `mago init` command …
=> feat(linter): add new psl plugin

crates/formatter/src/internal/format/mod.rs, crates/formatter/tests/cases/hooks_always_break/after.php, crates/formatter/tests/cases/hooks_always_break/before.php, crates/formatter/tests/cases/hooks_always_break/settings.inc, crates/formatter/tests/mod.rs
This PR modifies the formatter to always break property hooks (getters and setters) into multiple lines, regardless of the `print_width` setting.
Previously, property hooks were only broken into multiple lines if they didn't fit within the `print_width`. This could lead to unexpected single-line property hooks when users had a very large `print_width` value, compromising readability. This change ensures consistent formatting and improves readability for all users.
- **Feature:** Changed the formatter to always break property hooks into multiple lines.
- **Exception:** Property hook lists with no hooks ({}) remain on a single line.
- **Tests:** Updated test snapshots to reflect the new formatting.
Closes #124
=> feat(formatter): always break property hooks into multiple lines

crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/src/internal/format/member_access.rs, crates/formatter/src/internal/parens.rs, crates/formatter/tests/cases/issue_128/after.php, crates/formatter/tests/cases/issue_128/before.php, crates/formatter/tests/cases/issue_128/settings.inc, crates/formatter/tests/cases/issue_130/after.php, crates/formatter/tests/cases/issue_130/before.php, crates/formatter/tests/cases/issue_130/settings.inc, crates/formatter/tests/mod.rs
This PR addresses and fixes multiple bugs in the formatter related to argument lists, indentation, and member access chain breaking, as reported in issue #128.
The bugs fixed in this PR were causing incorrect formatting in specific scenarios involving argument lists, indentation within nested structures, and member access chain line breaking. These issues were reported by a user and negatively impacted the formatter's reliability and usability.
- **Bug Fix:** Fixed multiple bugs in the formatter related to argument lists printing, indentation, and member access chain breaking.
Closes #128
=> fix(formatter): correct argument printing and member access chain logic

crates/formatter/src/internal/format/array.rs, crates/formatter/src/internal/format/assignment.rs, crates/formatter/src/internal/format/call_arguments.rs, crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/member_access.rs, crates/formatter/src/internal/format/misc.rs, crates/formatter/src/internal/utils.rs, crates/formatter/src/lib.rs, crates/formatter/src/settings.rs, crates/formatter/tests/cases/preserve_breaking_conditional_expression/after.php, crates/formatter/tests/cases/preserve_breaking_conditional_expression/before.php, crates/formatter/tests/cases/preserve_breaking_conditional_expression/settings.inc, crates/formatter/tests/cases/preserve_breaking_conditional_expression_disabled/after.php, crates/formatter/tests/cases/preserve_breaking_conditional_expression_disabled/before.php, crates/formatter/tests/cases/preserve_breaking_conditional_expression_disabled/settings.inc, crates/formatter/tests/mod.rs, docs/formatter/settings.md
This PR adds a new configuration option to the formatter, `preserve_breaking_conditional_expression`.
This new option allows users to control the formatting of conditional (ternary) expressions. By enabling this option, users can preserve line breaks in conditional expressions, ensuring that their original formatting is maintained even if the expression could technically fit on a single line. This is particularly useful for improving the readability of complex or lengthy conditional expressions.
- **Feature:** Added preserve_breaking_conditional_expression option to preserve line breaks in conditional expressions.
- **Docs:** Updated the formatter documentation to include the new option.
- **Tests:** Added test cases to ensure the new option works as expected.
Closes #130
=> feat(formatter): add `preserve_breaking_conditional_expression` option

crates/formatter/src/internal/format/block.rs, crates/formatter/src/internal/format/class_like.rs, crates/formatter/src/internal/format/control_structure.rs, crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/misc.rs, crates/formatter/src/internal/format/mod.rs, crates/formatter/src/settings.rs, crates/formatter/tests/cases/inline_empty_braces_default/after.php, crates/formatter/tests/cases/inline_empty_braces_default/before.php, crates/formatter/tests/cases/inline_empty_braces_default/settings.inc, crates/formatter/tests/cases/inline_empty_braces_disabled/after.php, crates/formatter/tests/cases/inline_empty_braces_disabled/before.php, crates/formatter/tests/cases/inline_empty_braces_disabled/settings.inc, crates/formatter/tests/cases/inline_empty_braces_enabled/after.php, crates/formatter/tests/cases/inline_empty_braces_enabled/before.php, crates/formatter/tests/cases/inline_empty_braces_enabled/settings.inc, crates/formatter/tests/cases/inline_empty_braces_swapped/after.php, crates/formatter/tests/cases/inline_empty_braces_swapped/before.php, crates/formatter/tests/cases/inline_empty_braces_swapped/settings.inc, crates/formatter/tests/cases/issue_166/after.php, crates/formatter/tests/cases/parameter_attributes/after.php, crates/formatter/tests/mod.rs
This PR introduces new settings to control the inlining of empty braces for various language constructs (control structures, closures, functions, methods, constructors, class-like structures, and anonymous classes). It also adds a utility function to determine if a block is empty and refactors the code to consistently apply these settings.
Currently, the formatter lacks granular control over the placement of empty braces. This change addresses the need for more customization, allowing users to specify whether empty blocks should be inlined or placed on a new line based on the context. This enhances code readability and allows for better adherence to specific coding styles.
- **Feature**: Added `inline_empty_control_braces` setting.
- **Feature**: Added `inline_empty_closure_braces` …
=> feat(formatter): Add settings to inline empty braces

crates/linter/src/context.rs, crates/linter/src/plugin/strictness/rules/require_strict_types.rs
This pull request introduces an automatic fix for the rule `strictness/require_strict_types`. The fix adds `declare(strict_types=1);` after the opening tag.
When multiple files lack this statement, it's cumbersome to add them manually. It would be convenient that Mago take care of that.
Added a suggestion to the reported issue when `declare(strict_types=1)` is missing.
Closes https://github.com/carthage-software/mago/issues/145
- This is my first time installing and setting up Rust
- I couldn't find where to test the suggestion. My understanding is that the tests are generated thanks to the `RuleDefinition` examples, but I don't know how to test the fix plan from that.
=> feat(linter): add automatic fix for `strictness/require_strict_types`

crates/reporting/src/lib.rs, src/commands/lint.rs
Implement the `--minimum-level` flag in the `mago lint` command
Currently, we hardcode the failling threshold to `Level::Error`, and the logic for failling if at least one issue is found is already implemented, so the feature is pretty trivial to add :+1:
- **Feature:** `mago lint --minimum-level`
#174 
Still unsure about what type to use to represent `Level::FromStr::Err`. I think a simple `&'static str` should do the trick but I'd rather have some opinions first :+1:
Also not sure about the wording for the help message
=> feat(linter): implement `--mimimum-level` to lint command (#174)

Cargo.lock, Cargo.toml, crates/wasm/Cargo.toml
Allows `mago-formatter` to compile under wasm32-unknown-unknown.
To allow it to be used as a dprint plugin.
1. Disable `ahash` using the `getrandom` crate and instead use comptime randomness, which I believe is fine for these crates?
1. Upgrade blake3 which causes it to not use the `getrandom` crate.
1. I think we can now update the wasm crate to not require the "js" feature of getrandom and then remove it as a dependency.
None
=> fix: support compiling mago-formatter to wasm32-unknown-unknown

crates/linter/src/plugin/redundancy/rules/redundant_parentheses.rs, crates/linter/src/plugin/safety/rules/no_eval.rs, crates/linter/src/plugin/strictness/rules/no_empty_construct.rs, crates/linter/src/plugin/strictness/rules/no_shorthand_ternary.rs
Fixes spelling mistakes and makes sure messages start with a capital letter (to match the rest)
General improvement of message readability.
Fixed spelling mistakes and added missing capital letter at start of some messages.
=> fix: spelling/capitalization

crates/formatter/src/internal/parens.rs, crates/formatter/tests/cases/issue_241/after.php, crates/formatter/tests/cases/issue_241/before.php, crates/formatter/tests/cases/issue_241/settings.inc, crates/formatter/tests/mod.rs
Resolve #241 
Fixing a bug in the formatter that can cause runtime errors
Ensure `clone` followed by a binary expression are correctly parenthesized
#241
=> fix(formatter): Ensure clone binary operations are correctly parenthesized

.gitattributes, crates/formatter/tests/cases/issue_225/after.php, crates/formatter/tests/cases/issue_225/before.php, crates/formatter/tests/cases/issue_225/settings.inc, crates/formatter/tests/mod.rs, crates/syntax/src/lexer/mod.rs
Fix CRLF parsing inside heredocs.
Found an issue under Windows, when a .php file is uses CRLF line endings and has a heredoc.
- reproduce heredoc parsing failure when file uses CRLF line endings
- preserve CRLF in test fixture via `.gitattributes`
- fix lexer to accept `\r\n` line endings in heredoc/nowdoc openers
* fix .gitattributes & issue_225 test fixture to crlf
* Fix peeking inside DocumentKind::Heredoc
- `cargo test issue_225 --package mago-formatter -- --nocapture`
- `cargo test --workspace`
Closes #225
=> fix(syntax): CRLF heredoc parsing (#225)

docs/getting-started/cli.md
Removed about obsolete `mago fix` .
Update doc.
- **Docs:** Updated installation guide.
fix #282
=> fix(docs): remove `mago fix` reference

crates/formatter/src/internal/format/control_structure.rs, crates/formatter/src/internal/format/expression.rs, crates/formatter/src/internal/format/member_access.rs, crates/formatter/src/internal/format/misc.rs, crates/formatter/src/internal/parens.rs, crates/formatter/src/internal/utils.rs, crates/formatter/tests/cases/issue_279/after.php, crates/formatter/tests/cases/issue_279/before.php, crates/formatter/tests/cases/issue_279/settings.inc, crates/formatter/tests/cases/issue_300/after.php, crates/formatter/tests/cases/issue_300/before.php, crates/formatter/tests/cases/issue_300/settings.inc, crates/formatter/tests/cases/issue_301/after.php, crates/formatter/tests/cases/issue_301/before.php, crates/formatter/tests/cases/issue_301/settings.inc, crates/formatter/tests/mod.rs, crates/syntax/src/token/mod.rs
This commit resolves several formatting bugs related to operator associativity, spacing in `else if` chains, and comment alignment in control structures.
the primary change corrects how parentheses are handled for binary expressions. The formatter now respects operator associativity rules to preserve the original AST structure.
previously, expressions like `$a || ($b || $c)` were incorrectly flattened to `$a || $b || $c`, which is parsed differently. The new logic checks if an expression is the left or right child of a parent operator with the same precedence. It then correctly adds parentheses to maintain the intended evaluation order for both left-associative (e.g., `||`, `+`) and right-associative (e.g., `**`) operators.
closes #279
closes #300
closes #301
=> fix(formatter): correct parenthesis handling

.envrc, .gitignore, CONTRIBUTING.md, docs/contributing.md, flake.lock, flake.nix
This PR adds a `flake.nix` to provide a reproducible development environment for contributors using Nix, and updates the CONTRIBUTING guide with optional instructions for Nix users.
Setting up the exact Rust toolchain and dependencies can be error-prone, especially when the project requires Rust 1.89.0 and nightly for certain tasks (`just lint` / `just fix`).  
By providing a Nix flake, contributors on Linux or macOS can quickly enter a pré configured environment and start working without manual setup.
- **Feature:** Added `flake.nix` with Rust stable 1.89.0, nightly, OpenSSL, pkg-config, Just, and wasm-pack using `rustup`.
- **Docs:** Updated `CONTRIBUTING.md` with optional instructions for using `nix develop`.
https://github.com/carthage-software/mago/issues/371
- The flake uses …
=> chore(nix): add dev flake (rustup: 1.89.0 + nightly) and docs

crates/prelude/assets/extensions/standard.php
This PR fixes return type of the sizeof function, which is an alias of the count function => they should return the same thing.
- **Bug Fix:** Fixed `sizeof` function not having the same return type as `count` on non-empty-arrays.
=> fix(stubs): sizeof return type should be the same as count

crates/prelude/assets/extensions/standard.php
Update the `@return` docblock for the `end` function to be more precise, distinguishing between the return value for empty and non-empty arrays.
Fixes the following false positive
```php
<?php
/**
* @param non-empty-list<int> $test
*/
function x(array $test): int
{
$item = end($test);
return $item;
}
echo x([1]);
```
- **Bug Fix:** Updated the `@return` docblock for the `end` function to be more precise, distinguishing between the return value for empty and non-empty arrays. This results in a better and more precise analysis.
=> fix(stubs): refine end() return type annotation

crates/analyzer/tests/cases/use_inheritance_error_path.php, crates/codex/src/scanner/class_like.rs
Add support for `#[\Deprecated]` on traits, see https://wiki.php.net/rfc/deprecated_traits
PHP 8.5 adds support for using the `#[\Deprecated]` attribute on traits. When the attribute is present, PHP will emit deprecation warnings when the trait gets used. Since mago emits deprecation warnings when a trait documented with `@deprecated` is used, it seems sensible to also emit warnings when the deprecation is indicated via attribute.
- **Feature:** Expanded existing `analysis:deprecated-trait` warnings
Related to php/php-src#19045
=> feat(codex): add support for `#[\Deprecated]` on traits

crates/analyzer/src/utils/expression/array.rs, crates/analyzer/tests/cases/issue_390.php, crates/analyzer/tests/mod.rs
This PR fixes an issue when checking for an array key presence, and then accessing a different one. Mago will now properly report an error.
fixes #390 
- **Bug Fix:** The analyzer will now properly report error when checking for a key presence and accessing a different one later.
fixes #390
=> fix(analyzer): incorrect behavior with allow-possibly-undefined-array-keys

crates/analyzer/src/utils/docblock.rs, crates/codex/src/scanner/function_like.rs, crates/docblock/src/tag.rs
Refactors the docblock parsing and consumption flow by introducing a structured `Variable` type (with variadic and by‑reference flags), normalizing variable names for matching, and improving diagnostics formatting. The change reduces duplicated logic across crates and clarifies how variable tokens are handled.
Feedback on #376 suggested going beyond keeping raw strings and modeling variables explicitly.
- Refactor(docblock): add `Variable { name, is_variadic, is_by_reference }` (name includes `$`, excludes leading `...` and `&`).
- Refactor(docblock): `parse_var_ident` returns `Option<Variable>`; `ParameterTag`/`ParameterOutTag`/`AssertionTag`/`VarTag` now carry `Variable`.
- Ergonomics: implement `Display` for `Variable` so messages render as "&...$name". Remove unused helpers.
- …
=> refactor(docblock): add variable struct

crates/analyzer/src/invocation/special_function_like_handler/mod.rs, crates/analyzer/src/invocation/special_function_like_handler/standard/array.rs, crates/analyzer/src/invocation/special_function_like_handler/standard/mod.rs, crates/analyzer/tests/cases/issue_275.php, crates/analyzer/tests/mod.rs, crates/codex/src/ttype/union.rs, crates/prelude/assets/extensions/standard.php
This PR allows us to correctly type arrays/lists created by array_column, when an array of Named Objects is passed as the first argument.
- **Feature:** The analyzer can now correctly deduce the type when array of classes is passed into the `array_column` function.
closes #275
there are some allocations, please review and tell me how to ideally get rid of them.
also, maybe some more errors are needed.
=> feat(analyzer): allow lists/arrays of Named Objects to be passed into array_column

crates/analyzer/src/expression/clone.rs, crates/analyzer/tests/cases/issue_415.php, crates/analyzer/tests/mod.rs
This PR fixes type recognition when using clone $this inside a trait object.
- **Bug Fix:** Fixed not being able to call clone on Trait objects, the analyzer will now properly assert a better type.
fixed #415 
There is another "bug", when returning `$this` or a clone of `$this`, and we return static. Maybe we should look who's calling the method and return `T` instead of `T&static`.
=> fix(analyzer): clone type recognition inside traits

README.md
Provides an updated link for PHP CodeSniffer in the README.
The repo linked to is no longer current.
- **Docs:** Updated README.
=> docs: update link for PHP CodeSniffer

flake.nix
Adds `rustc` and `cargo` to the `flake.nix` packages.
As of `nixos-25.05` (stable) the cargo and rustc versions were not up-to-date
enough to compile Mago. Including them explicitly in the `flake.nix`
ensures that mago can be compiled in the development shell.
---
As an aside I'm the maintainer of the Phpactor language server, and I'm looking
forward to the day that I'm not :sweat_smile: but jokes-aside just dropping a
note here to offer my support and will be keeping an eye on the progress as
I'm sure this project will provide a responsive and reliable PHP language
server!
=> Include Cargo and Rustc in flake.nix

crates/prelude/assets/extensions/session.php, crates/prelude/assets/extensions/standard.php
Small fix in the session_id() stub.
See https://www.php.net/manual/de/function.session-id.php for refrence
Unexpected errors get thrown by mago anlyze.
```
error[too-few-arguments]: Too few arguments provided for function `session_id`.
┌─ php_source\lib\index.php:151:25
│
151 │ $session_id = session_id();
│               ----------^^ More arguments expected here
│               │
│               For this function call
│
= Expected at least 1 argument(s) for non-optional parameters, but received 0.
= Help: Provide all required arguments.
```
- **Bug Fix:** Fixed Stub
-
=> fix: make session argument optional

crates/linter/src/rule/mod.rs, crates/linter/src/rule/redundancy/mod.rs, crates/linter/src/rule/redundancy/no_redundant_readonly.rs, crates/linter/src/settings.rs, docs/tools/linter/rules/redundancy.md
In a readonly class, properties don't need their own readonly qualifiers.
This adds a linter rule that checks for redundant `readonly` modifiers
Similar to the check for `final` modifiers, this adds a feature to detect redundant code.
- **Feature:** Added a linter rule for redundant `readonly` properties.
None
None
=> feat(linter): lint redundant readonly modifiers

crates/linter/src/rule/redundancy/no_redundant_final.rs
This extends the linter rule for redundant `final` modifiers with a fixer feature to automatically remove the redundant modifier.
It adds the fixer feature to the existing no-redundant-final rule.
- **Feature:** Added support to automatically remove redundant `final` modifiers.
This was suggested in PR #522
None
=> feat(linter): Add a fixer action for redundant final modifiers
